on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Release

jobs:
  Release:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-24.04}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install XQuartz on MacOS
        if: runner.os == 'macOS'
        run: |
            brew install --cask xquartz

      - name: Install XQuartz on MacOS
        if: runner.os == 'Linux'
        run: |
            apt update
            apt install -y \
              cmake \
              build-essential \
              gfortran \
              git \
              libopenblas-dev \
              libopenmpi-dev \
              openmpi-bin 


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
